figure('name', 'M=1 R=1', 'color','white');
subplot(2,3,1);
plot(flow(:,1),flow(:,2), '-k');
grid on;
grid minor;
xlabel('t');
ylabel('Flow');
subplot(2,3,2);
plot(i(:,1),i(:,2), '-k');
xlabel('t');
ylabel('iг');
subplot(2,3,3);
plot(w(:,1),w(:,2), '-k');
grid on;
grid minor;
xlabel('t');
ylabel('w');
subplot(2,3,2);
grid on;
grid minor;
subplot(2,3,4);
plot(flow(:,2),i(:,2), '-k');
grid on;
grid minor;
xlabel('Flow');
ylabel('iг');
subplot(2,3,5);
plot(flow(:,2),w(:,2), '-k');
grid on; 
grid minor;
xlabel('Flow'); 
ylabel('w')
subplot(2,3,6);
plot(i(:,2),w(:,2), '-k');
grid on; 
grid minor;
xlabel('iг'); 
ylabel('w');
